apiVersion: apps/v1
kind: Deployment
metadata:
  name: phone-gateway
  namespace: ai-ninja
  labels:
    app: phone-gateway
    tier: core
    version: v1
    app.kubernetes.io/name: phone-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: ai-ninja
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: phone-gateway
  template:
    metadata:
      labels:
        app: phone-gateway
        tier: core
        version: v1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3001"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: phone-gateway-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: phone-gateway
        image: ai-ninja/phone-gateway:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3001
          protocol: TCP
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: redis-url
        - name: AZURE_COMMUNICATION_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: communication-connection-string
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: postgres-url
        envFrom:
        - configMapRef:
            name: app-config
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
            ephemeral-storage: 1Gi
          limits:
            cpu: 1000m
            memory: 2Gi
            ephemeral-storage: 2Gi
        livenessProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /ready
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
        startupProbe:
          httpGet:
            path: /health
            port: http
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 6
          successThreshold: 1
        volumeMounts:
        - name: logs
          mountPath: /app/logs
        - name: temp-storage
          mountPath: /app/temp
      volumes:
      - name: logs
        emptyDir:
          sizeLimit: 1Gi
      - name: temp-storage
        emptyDir:
          sizeLimit: 2Gi
      nodeSelector:
        node-type: compute
      tolerations:
      - key: "node-type"
        operator: "Equal"
        value: "compute"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - phone-gateway
              topologyKey: kubernetes.io/hostname
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-type
                operator: In
                values:
                - compute
                - general
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: phone-gateway-service
  namespace: ai-ninja
  labels:
    app: phone-gateway
    tier: core
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: phone-gateway
  ports:
  - name: http
    port: 80
    targetPort: 3001
    protocol: TCP
  - name: https
    port: 443
    targetPort: 3001
    protocol: TCP
  sessionAffinity: ClientIP

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: phone-gateway-sa
  namespace: ai-ninja
  labels:
    app: phone-gateway
    tier: core

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: ai-ninja
  name: phone-gateway-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: phone-gateway-rolebinding
  namespace: ai-ninja
subjects:
- kind: ServiceAccount
  name: phone-gateway-sa
  namespace: ai-ninja
roleRef:
  kind: Role
  name: phone-gateway-role
  apiGroup: rbac.authorization.k8s.io