global:
  scrape_interval: 30s
  evaluation_interval: 30s
  external_labels:
    cluster: 'ai-ninja-dev'
    environment: 'development'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'user-management'
    static_configs:
      - targets: ['user-management:3005']
    metrics_path: '/metrics'
    scrape_interval: 15s

  - job_name: 'realtime-processor' 
    static_configs:
      - targets: ['realtime-processor:3002']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

  - job_name: 'service-health'
    static_configs:
      - targets: 
        - 'user-management:3005'
        - 'realtime-processor:3002'
        - 'nginx:80'
    metrics_path: '/health'
    scrape_interval: 30s