# Development Environment Configuration
# Local development environment with Docker Compose

# Environment Info
ENVIRONMENT=development
NODE_ENV=development
LOG_LEVEL=debug

# Database Configuration (Development)
DB_HOST=postgres-dev
DB_PORT=5432
DB_NAME=ai_ninja_dev
DB_USERNAME=ai_ninja_dev
DB_PASSWORD=dev_password_123
DB_MAX_CONNECTIONS=10
DB_CONNECTION_TIMEOUT=5000
DB_SSL=false

# Redis Configuration (Development)
REDIS_HOST=redis-dev
REDIS_PORT=6379
REDIS_DB=0
REDIS_PASSWORD=dev_redis_123

# Application Ports (Docker Compose)
USER_MANAGEMENT_PORT=3005
SMART_WHITELIST_PORT=3006
REALTIME_PROCESSOR_PORT=3002
CONVERSATION_ENGINE_PORT=3003
PROFILE_ANALYTICS_PORT=3004
CONVERSATION_ANALYZER_PORT=3007

# Docker Registry (Local)
DOCKER_REGISTRY=local
REGISTRY_URL=localhost:5000

# Azure Services (Development/Mock)
AZURE_SPEECH_REGION=eastus
AZURE_SPEECH_KEY=mock_speech_key_development
AZURE_OPENAI_ENDPOINT=http://localhost:8080/mock-openai
AZURE_OPENAI_KEY=mock_openai_key_development

# Security Settings (Relaxed for Development)
JWT_ACCESS_SECRET=development_jwt_access_secret_key
JWT_REFRESH_SECRET=development_jwt_refresh_secret_key
JWT_EXPIRES_IN=24h
JWT_REFRESH_EXPIRES_IN=30d
SESSION_SECRET=development_session_secret_key
SESSION_TIMEOUT=3600

# Feature Flags (Development)
FEATURE_EMAIL_VERIFICATION_REQUIRED=false
FEATURE_MFA_REQUIRED=false
FEATURE_RATE_LIMITING_ENABLED=false
FEATURE_AUDIT_LOGGING_ENABLED=true
FEATURE_SECURITY_HEADERS_ENABLED=false
FEATURE_MOCK_AZURE_SERVICES=true

# Performance Settings (Relaxed for Development)
MAX_CONCURRENT_CALLS=100
WEBSOCKET_TIMEOUT=600000
HTTP_TIMEOUT=60000
AUDIO_PROCESSING_TIMEOUT=10000
PROCESSING_PIPELINE_TIMEOUT=3000

# Development-Specific Settings
HOT_RELOAD_ENABLED=true
DEBUG_MODE=true
DEV_TOOLS_ENABLED=true
MOCK_EXTERNAL_SERVICES=true
SKIP_MIGRATIONS=false
RESET_DB_ON_START=false

# CORS Configuration (Permissive for Development)
CORS_ORIGINS=http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000
CORS_CREDENTIALS=true

# Logging Configuration
LOG_TO_FILE=false
LOG_TO_CONSOLE=true
LOG_STRUCTURED=false

# Testing Configuration
TEST_DB_NAME=ai_ninja_test
TEST_REDIS_DB=1
ENABLE_TEST_ENDPOINTS=true

# Monitoring (Development)
METRICS_ENABLED=true
HEALTH_CHECK_INTERVAL=30
PROMETHEUS_METRICS_PORT=9090

# File Upload (Development)
UPLOAD_MAX_SIZE=100MB
UPLOAD_TEMP_DIR=/tmp/uploads

# Rate Limiting (Disabled/Relaxed)
RATE_LIMIT_ENABLED=false
RATE_LIMIT_WINDOW=3600
RATE_LIMIT_MAX_REQUESTS=10000

# Email Configuration (Mock)
EMAIL_PROVIDER=mock
SMTP_HOST=localhost
SMTP_PORT=1025
SMTP_USERNAME=dev
SMTP_PASSWORD=dev