# =============================================================================
# Horizontal Pod Autoscaler (HPA) Configurations
# Auto-scaling policies for all AI Answer Ninja services
# =============================================================================

# =============================================================================
# Core Services HPA
# =============================================================================

# Phone Gateway HPA - Scales based on CPU and custom metrics
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: phone-gateway-hpa
  namespace: ai-ninja
  labels:
    app: phone-gateway
    tier: core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phone-gateway
  minReplicas: 2
  maxReplicas: 20
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metric: incoming calls per second
  - type: Pods
    pods:
      metric:
        name: incoming_calls_per_second
      target:
        type: AverageValue
        averageValue: "50"
  # Custom metric: request queue length
  - type: Pods
    pods:
      metric:
        name: request_queue_length
      target:
        type: AverageValue
        averageValue: "100"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      - type: Pods
        value: 4
        periodSeconds: 30
      selectPolicy: Max

---
# Realtime Processor HPA - More conservative scaling due to resource intensity
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: realtime-processor-hpa
  namespace: ai-ninja
  labels:
    app: realtime-processor
    tier: core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: realtime-processor
  minReplicas: 2
  maxReplicas: 10
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  # Custom metric: active WebSocket connections
  - type: Pods
    pods:
      metric:
        name: active_websocket_connections
      target:
        type: AverageValue
        averageValue: "100"
  # Custom metric: audio processing queue length
  - type: Pods
    pods:
      metric:
        name: audio_processing_queue_length
      target:
        type: AverageValue
        averageValue: "20"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600  # Longer stabilization for resource-intensive service
      policies:
      - type: Percent
        value: 20
        periodSeconds: 120
      - type: Pods
        value: 1
        periodSeconds: 120
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max

---
# Conversation Engine HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: conversation-engine-hpa
  namespace: ai-ninja
  labels:
    app: conversation-engine
    tier: core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: conversation-engine
  minReplicas: 2
  maxReplicas: 15
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  # Custom metric: AI requests per second
  - type: Pods
    pods:
      metric:
        name: ai_requests_per_second
      target:
        type: AverageValue
        averageValue: "30"
  # Custom metric: average response time
  - type: Pods
    pods:
      metric:
        name: average_response_time_ms
      target:
        type: AverageValue
        averageValue: "1000"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 15
        periodSeconds: 90
      - type: Pods
        value: 1
        periodSeconds: 90
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 90
      policies:
      - type: Percent
        value: 75
        periodSeconds: 45
      - type: Pods
        value: 3
        periodSeconds: 45
      selectPolicy: Max

---
# Profile Analytics HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: profile-analytics-hpa
  namespace: ai-ninja
  labels:
    app: profile-analytics
    tier: core
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: profile-analytics
  minReplicas: 2
  maxReplicas: 12
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metric: ML processing queue length
  - type: Pods
    pods:
      metric:
        name: ml_processing_queue_length
      target:
        type: AverageValue
        averageValue: "50"
  # Custom metric: analytics requests per second
  - type: Pods
    pods:
      metric:
        name: analytics_requests_per_second
      target:
        type: AverageValue
        averageValue: "25"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 450
      policies:
      - type: Percent
        value: 25
        periodSeconds: 120
      - type: Pods
        value: 1
        periodSeconds: 120
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Max

---
# =============================================================================
# Support Services HPA
# =============================================================================

# User Management HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-management-hpa
  namespace: ai-ninja
  labels:
    app: user-management
    tier: support
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-management
  minReplicas: 2
  maxReplicas: 8
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  # Custom metric: authentication requests per second
  - type: Pods
    pods:
      metric:
        name: auth_requests_per_second
      target:
        type: AverageValue
        averageValue: "100"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 30
      selectPolicy: Max

---
# Smart Whitelist HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: smart-whitelist-hpa
  namespace: ai-ninja
  labels:
    app: smart-whitelist
    tier: support
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: smart-whitelist
  minReplicas: 2
  maxReplicas: 10
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
  # Custom metric: whitelist lookups per second
  - type: Pods
    pods:
      metric:
        name: whitelist_lookups_per_second
      target:
        type: AverageValue
        averageValue: "200"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 25
        periodSeconds: 90
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 90
      policies:
      - type: Percent
        value: 75
        periodSeconds: 45
      selectPolicy: Max

---
# =============================================================================
# Platform Services HPA
# =============================================================================

# Configuration Service HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: configuration-hpa
  namespace: ai-ninja
  labels:
    app: configuration
    tier: platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: configuration
  minReplicas: 2
  maxReplicas: 6
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 25
        periodSeconds: 30
      selectPolicy: Max

---
# Storage Service HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: storage-hpa
  namespace: ai-ninja
  labels:
    app: storage
    tier: platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: storage
  minReplicas: 2
  maxReplicas: 8
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75
  # Custom metric: file upload requests per second
  - type: Pods
    pods:
      metric:
        name: file_upload_requests_per_second
      target:
        type: AverageValue
        averageValue: "50"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 20
        periodSeconds: 90
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 90
      policies:
      - type: Percent
        value: 50
        periodSeconds: 45
      selectPolicy: Max

---
# Monitoring Service HPA
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: monitoring-hpa
  namespace: ai-ninja
  labels:
    app: monitoring
    tier: platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: monitoring
  minReplicas: 2
  maxReplicas: 6
  metrics:
  # CPU-based scaling
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 75
  # Memory-based scaling
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  # Custom metric: metrics ingestion rate
  - type: Pods
    pods:
      metric:
        name: metrics_ingestion_rate
      target:
        type: AverageValue
        averageValue: "1000"
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 15
        periodSeconds: 120
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      selectPolicy: Max

---
# =============================================================================
# Vertical Pod Autoscaler (VPA) for Resource Optimization
# =============================================================================

# Phone Gateway VPA
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: phone-gateway-vpa
  namespace: ai-ninja
  labels:
    app: phone-gateway
    tier: core
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: phone-gateway
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: phone-gateway
      minAllowed:
        cpu: 100m
        memory: 256Mi
      maxAllowed:
        cpu: 2000m
        memory: 4Gi
      controlledResources: ["cpu", "memory"]

---
# Realtime Processor VPA
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: realtime-processor-vpa
  namespace: ai-ninja
  labels:
    app: realtime-processor
    tier: core
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: realtime-processor
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: realtime-processor
      minAllowed:
        cpu: 250m
        memory: 512Mi
      maxAllowed:
        cpu: 4000m
        memory: 8Gi
      controlledResources: ["cpu", "memory"]

---
# =============================================================================
# PodDisruptionBudget for High Availability
# =============================================================================

# Phone Gateway PDB
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: phone-gateway-pdb
  namespace: ai-ninja
  labels:
    app: phone-gateway
    tier: core
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: phone-gateway
      tier: core

---
# Realtime Processor PDB
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: realtime-processor-pdb
  namespace: ai-ninja
  labels:
    app: realtime-processor
    tier: core
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: realtime-processor
      tier: core

---
# Conversation Engine PDB
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: conversation-engine-pdb
  namespace: ai-ninja
  labels:
    app: conversation-engine
    tier: core
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: conversation-engine
      tier: core

---
# Profile Analytics PDB
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: profile-analytics-pdb
  namespace: ai-ninja
  labels:
    app: profile-analytics
    tier: core
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: profile-analytics
      tier: core

---
# User Management PDB
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: user-management-pdb
  namespace: ai-ninja
  labels:
    app: user-management
    tier: support
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: user-management
      tier: support

---
# Smart Whitelist PDB
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: smart-whitelist-pdb
  namespace: ai-ninja
  labels:
    app: smart-whitelist
    tier: support
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: smart-whitelist
      tier: support