groups:
  # 服务可用性告警
  - name: service_availability
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is down"
          description: "Service {{ $labels.job }} on instance {{ $labels.instance }} has been down for more than 30 seconds."

      - alert: HighErrorRate
        expr: rate(http_requests_total{code=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "High error rate on {{ $labels.job }}"
          description: "Error rate is {{ $value }}% on service {{ $labels.job }} for more than 2 minutes."

  # 性能相关告警
  - name: performance_alerts
    rules:
      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2.0
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency detected on {{ $labels.job }}"
          description: "95th percentile latency is {{ $value }}s on service {{ $labels.job }} for more than 5 minutes."

      - alert: VoiceProcessingLatency
        expr: histogram_quantile(0.95, rate(voice_processing_duration_seconds_bucket[5m])) > 1.5
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Voice processing latency too high"
          description: "95th percentile voice processing latency is {{ $value }}s, exceeding 1.5s threshold."

      - alert: AIResponseLatency
        expr: histogram_quantile(0.95, rate(ai_response_duration_seconds_bucket[5m])) > 3.0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "AI response latency too high"
          description: "95th percentile AI response latency is {{ $value }}s, exceeding 3s threshold."

  # 资源使用告警
  - name: resource_usage
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg(irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}% on instance {{ $labels.instance }} for more than 5 minutes."

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}% on instance {{ $labels.instance }} for more than 5 minutes."

      - alert: HighDiskUsage
        expr: (node_filesystem_size_bytes{fstype!="tmpfs"} - node_filesystem_free_bytes{fstype!="tmpfs"}) / node_filesystem_size_bytes{fstype!="tmpfs"} * 100 > 85
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "High disk usage detected"
          description: "Disk usage is {{ $value }}% on mount {{ $labels.mountpoint }} for more than 10 minutes."

  # 数据库相关告警
  - name: database_alerts
    rules:
      - alert: PostgreSQLDown
        expr: pg_up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database is down on instance {{ $labels.instance }}."

      - alert: PostgreSQLTooManyConnections
        expr: pg_stat_activity_count / pg_settings_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL too many connections"
          description: "PostgreSQL connection usage is {{ $value }}% on instance {{ $labels.instance }}."

      - alert: PostgreSQLSlowQueries
        expr: rate(pg_stat_database_tup_fetched[5m]) / rate(pg_stat_database_tup_returned[5m]) < 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "PostgreSQL slow queries detected"
          description: "PostgreSQL query efficiency is low on database {{ $labels.datname }}."

      - alert: RedisDown
        expr: redis_up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Redis is down"
          description: "Redis server is down on instance {{ $labels.instance }}."

      - alert: RedisHighMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 90
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis high memory usage"
          description: "Redis memory usage is {{ $value }}% on instance {{ $labels.instance }}."

  # 业务逻辑告警
  - name: business_alerts
    rules:
      - alert: HighCallVolume
        expr: rate(phone_calls_total[5m]) > 100
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High call volume detected"
          description: "Call rate is {{ $value }} calls/second, which may indicate unusual activity."

      - alert: LowWhitelistHitRate
        expr: rate(whitelist_hits_total[10m]) / rate(phone_calls_total[10m]) * 100 < 10
        for: 10m
        labels:
          severity: info
        annotations:
          summary: "Low whitelist hit rate"
          description: "Whitelist hit rate is {{ $value }}%, which may indicate spam attack."

      - alert: AIClassificationFailure
        expr: rate(ai_classification_errors_total[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "AI classification failures detected"
          description: "AI classification error rate is {{ $value }} errors/second."

      - alert: VoiceProcessingQueueBacklog
        expr: voice_processing_queue_size > 50
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Voice processing queue backlog"
          description: "Voice processing queue has {{ $value }} pending jobs."

  # 安全相关告警
  - name: security_alerts
    rules:
      - alert: HighFailedLoginRate
        expr: rate(auth_failed_total[5m]) > 5
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "High failed login rate detected"
          description: "Failed login rate is {{ $value }} attempts/second from {{ $labels.source_ip }}."

      - alert: UnauthorizedAPIAccess
        expr: rate(http_requests_total{code="401"}[5m]) > 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "High unauthorized access attempts"
          description: "Unauthorized API access rate is {{ $value }} requests/second on {{ $labels.job }}."

      - alert: SuspiciousCallPattern
        expr: rate(phone_calls_total{spam_category="suspicious"}[10m]) > 20
        for: 5m
        labels:
          severity: info
        annotations:
          summary: "Suspicious call pattern detected"
          description: "Suspicious call rate is {{ $value }} calls/second, monitoring for potential attack."

  # Kubernetes相关告警（生产环境）
  - name: kubernetes_alerts
    rules:
      - alert: KubernetesPodCrashLooping
        expr: rate(kube_pod_container_status_restarts_total[15m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Pod {{ $labels.pod }} is crash looping"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is restarting frequently."

      - alert: KubernetesNodeNotReady
        expr: kube_node_status_condition{condition="Ready", status="true"} == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Kubernetes node not ready"
          description: "Node {{ $labels.node }} is not ready for more than 5 minutes."

      - alert: KubernetesPodPending
        expr: kube_pod_status_phase{phase="Pending"} == 1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Pod stuck in pending state"
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is pending for more than 10 minutes."