# Production Environment Configuration
# Production-ready configuration with maximum security and performance

# Environment Info
ENVIRONMENT=production
NODE_ENV=production
LOG_LEVEL=warn

# Kubernetes Configuration
NAMESPACE=ai-ninja
KUBECONFIG=/path/to/production-kubeconfig
CLUSTER_CONTEXT=production-cluster

# Database Configuration (Production)
DB_HOST=postgresql-production.internal
DB_PORT=5432
DB_NAME=ai_ninja_production
DB_MAX_CONNECTIONS=25
DB_CONNECTION_TIMEOUT=3000
DB_SSL=true
DB_SSL_REQUIRE=true
DB_SSL_CERT_PATH=/etc/ssl/certs/postgresql-production.crt
DB_READ_REPLICA_ENABLED=true
DB_READ_REPLICA_HOST=postgresql-replica.internal

# Redis Configuration (Production)
REDIS_HOST=redis-production.internal
REDIS_PORT=6379
REDIS_DB=0
REDIS_CLUSTER_MODE=true
REDIS_SENTINEL_ENABLED=true
REDIS_PASSWORD_REQUIRED=true

# Docker Registry (Production)
DOCKER_REGISTRY=ghcr.io/ai-ninja
REGISTRY_URL=ghcr.io
PUSH_IMAGES=true
IMAGE_SECURITY_SCANNING=true

# Azure Services (Production)
AZURE_SPEECH_REGION=eastus2
AZURE_OPENAI_ENDPOINT=https://ai-ninja-prod-openai.openai.azure.com
AZURE_SPEECH_ENDPOINT=https://ai-ninja-prod-speech.cognitiveservices.azure.com

# Security Settings (Maximum Security)
JWT_EXPIRES_IN=30m
JWT_REFRESH_EXPIRES_IN=24h
SESSION_TIMEOUT=900
PASSWORD_MIN_LENGTH=16
PASSWORD_REQUIRE_SPECIAL_CHARS=true
PASSWORD_REQUIRE_NUMBERS=true
PASSWORD_REQUIRE_UPPERCASE=true
PASSWORD_REQUIRE_LOWERCASE=true
PASSWORD_HISTORY_CHECK=5

# Feature Flags (Production)
FEATURE_EMAIL_VERIFICATION_REQUIRED=true
FEATURE_MFA_REQUIRED=true
FEATURE_RATE_LIMITING_ENABLED=true
FEATURE_AUDIT_LOGGING_ENABLED=true
FEATURE_SECURITY_HEADERS_ENABLED=true
FEATURE_MOCK_AZURE_SERVICES=false

# Performance Settings (Optimized for Production)
MAX_CONCURRENT_CALLS=2000
WEBSOCKET_TIMEOUT=180000
HTTP_TIMEOUT=15000
AUDIO_PROCESSING_TIMEOUT=3000
PROCESSING_PIPELINE_TIMEOUT=800

# Scaling Configuration (Production)
MIN_REPLICAS_CRITICAL=5
MIN_REPLICAS_STANDARD=3
MAX_REPLICAS_CRITICAL=25
MAX_REPLICAS_STANDARD=15
TARGET_CPU_UTILIZATION=60
TARGET_MEMORY_UTILIZATION=70
SCALE_UP_COOLDOWN=60
SCALE_DOWN_COOLDOWN=300

# CORS Configuration (Strict)
CORS_ORIGINS=https://app.ai-ninja.com,https://admin.ai-ninja.com
CORS_CREDENTIALS=true
CORS_MAX_AGE=86400

# Logging Configuration (Production)
LOG_TO_FILE=true
LOG_TO_CONSOLE=false
LOG_STRUCTURED=true
LOG_RETENTION_DAYS=90
LOG_COMPRESSION_ENABLED=true
LOG_ENCRYPTION_ENABLED=true

# Monitoring (Comprehensive)
METRICS_ENABLED=true
HEALTH_CHECK_INTERVAL=5
PROMETHEUS_METRICS_PORT=9090
JAEGER_ENABLED=true
GRAFANA_ENABLED=true
ALERTING_ENABLED=true
SENTRY_ENABLED=true

# Storage Configuration (Production)
STORAGE_CLASS=fast-ssd
BACKUP_ENABLED=true
BACKUP_RETENTION_DAYS=90
BACKUP_SCHEDULE=0 1 * * *
BACKUP_ENCRYPTION=true
DISASTER_RECOVERY_ENABLED=true

# Rate Limiting (Strict)
RATE_LIMIT_ENABLED=true
RATE_LIMIT_WINDOW=300
RATE_LIMIT_MAX_REQUESTS=100
RATE_LIMIT_BURST_SIZE=20
RATE_LIMIT_REDIS_KEY_PREFIX=prod:rate_limit

# SSL/TLS Configuration (Strict)
SSL_ENABLED=true
CERT_MANAGER_ISSUER=letsencrypt-prod
FORCE_HTTPS=true
HSTS_ENABLED=true
HSTS_MAX_AGE=31536000
TLS_MIN_VERSION=1.2

# Email Configuration (Production)
EMAIL_PROVIDER=azure_communication_services
EMAIL_FROM=noreply@ai-ninja.com
EMAIL_REPLY_TO=support@ai-ninja.com

# Production Testing
INTEGRATION_TESTS_ENABLED=false
LOAD_TESTING_ENABLED=false
SMOKE_TESTS_ENABLED=true
CANARY_DEPLOYMENT_ENABLED=true

# External Services (Production)
EXTERNAL_API_TIMEOUT=5000
RETRY_ATTEMPTS=3
RETRY_BACKOFF=exponential
CIRCUIT_BREAKER_ENABLED=true
CIRCUIT_BREAKER_THRESHOLD=5
CIRCUIT_BREAKER_TIMEOUT=30000

# Cache Configuration (Optimized)
CACHE_TTL_DEFAULT=1800
CACHE_TTL_USER_PROFILE=900
CACHE_TTL_WHITELIST=300
CACHE_WARMING_ENABLED=true
CACHE_COMPRESSION_ENABLED=true

# Security Scanning (Production)
SECURITY_SCANNING_ENABLED=true
VULNERABILITY_SCANNING_SCHEDULE=0 2 * * *
DEPENDENCY_SCANNING_ENABLED=true
SAST_SCANNING_ENABLED=true
DAST_SCANNING_ENABLED=true

# Compliance Settings
GDPR_COMPLIANCE_ENABLED=true
DATA_RETENTION_POLICY_ENABLED=true
AUDIT_LOG_RETENTION_DAYS=2555  # 7 years
PII_ENCRYPTION_ENABLED=true
RIGHT_TO_BE_FORGOTTEN_ENABLED=true

# Performance Optimization
CONNECTION_POOLING_ENABLED=true
QUERY_CACHING_ENABLED=true
RESPONSE_COMPRESSION_ENABLED=true
CDN_ENABLED=true
EDGE_CACHING_ENABLED=true

# Business Continuity
HIGH_AVAILABILITY_ENABLED=true
MULTI_AZ_DEPLOYMENT=true
DISASTER_RECOVERY_RPO=1h
DISASTER_RECOVERY_RTO=4h
FAILOVER_TESTING_ENABLED=true

# Resource Limits (Production)
CPU_REQUEST_MIN=100m
CPU_LIMIT_MAX=2000m
MEMORY_REQUEST_MIN=256Mi
MEMORY_LIMIT_MAX=4Gi
STORAGE_REQUEST_MIN=10Gi
STORAGE_LIMIT_MAX=1Ti

# Network Security
NETWORK_POLICIES_ENABLED=true
POD_SECURITY_STANDARDS=restricted
SERVICE_MESH_ENABLED=true
MTLS_ENABLED=true
INGRESS_WAF_ENABLED=true

# Cost Optimization
AUTO_SCALING_ENABLED=true
RESOURCE_OPTIMIZATION_ENABLED=true
COST_MONITORING_ENABLED=true
UNUSED_RESOURCE_CLEANUP=true

# Data Protection
ENCRYPTION_AT_REST_ENABLED=true
ENCRYPTION_IN_TRANSIT_ENABLED=true
KEY_ROTATION_ENABLED=true
KEY_ROTATION_SCHEDULE=0 3 1 */3 *  # Quarterly
BACKUP_ENCRYPTION_ENABLED=true